# -*- coding: utf-8 -*-
"""innomatics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xw4wVv-LLJ2_va9nPkqG6vkyq_GZa1UX?usp=sharing
"""

INNOMATICS HACKALTHON PROJECT

import pandas as pd

"""LOADING DATA FROM VERY FILE"""

orders = pd.read_csv("/content/orders.csv")
orders.head()

users = pd.read_json("/content/users.json")
users.head()

import sqlite3

conn = sqlite3.connect("restaurants.db")
with open("/content/restaurants.sql", "r") as f:
    conn.executescript(f.read())

restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

"""MERGING"""

orders_users = pd.merge(
    orders,
    users,
    on="user_id",
    how="left"
)

final_df = pd.merge(
    orders_users,
    restaurants,
    on="restaurant_id",
    how="left"
)

final_df.to_csv("final_food_delivery_dataset.csv", index=False)

from google.colab import files
files.download("final_food_delivery_dataset.csv")

"""DOWNLAODED THE MERGED FILE"""

df = pd.read_csv("/content/final_food_delivery_dataset.csv")
df.head()

"""RENAMING FILES"""

df.columns

df = df.rename(columns={
    'membership': 'membership_type',
    'restaurant_name_y': 'restaurant_name',
    'name': 'user_name'
})

df = df.drop(columns=['restaurant_name_x'])

df.columns

"""Which city has the highest total revenue (total_amount) from Gold members?  

"""

df[df['membership_type'] == 'Gold'] \
  .groupby('city')['total_amount'] \
  .sum() \
  .sort_values(ascending=False)

"""Which cuisine has the highest average order value across all orders?

"""

df.groupby('cuisine')['total_amount'] \
  .mean() \
  .sort_values(ascending=False)

"""How many distinct users placed orders worth more than ₹1000 in total (sum of all their orders)?

"""

high_spenders = df.groupby('user_id')['total_amount'].sum()
count_users = high_spenders[high_spenders > 1000].count()
count_users

"""Which restaurant rating range generated the highest total revenue?

"""

bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['3.0 – 3.5', '3.6 – 4.0', '4.1 – 4.5', '4.6 – 5.0']

df['rating_range'] = pd.cut(df['rating'], bins=bins, labels=labels)

df.groupby('rating_range')['total_amount'] \
  .sum() \
  .sort_values(ascending=False)

"""Among Gold members, which city has the highest average order value?

"""

df[df['membership_type'] == 'Gold'] \
  .groupby('city')['total_amount'] \
  .mean() \
  .sort_values(ascending=False)

Which cuisine has the lowest number of distinct restaurants but still contributes significant revenue?

restaurant_count = df.groupby('cuisine')['restaurant_id'].nunique()
revenue = df.groupby('cuisine')['total_amount'].sum()

summary = pd.concat([restaurant_count, revenue], axis=1)
summary.columns = ['restaurant_count', 'total_revenue']

summary.sort_values(by='restaurant_count')

"""What percentage of total orders were placed by Gold members? (Rounded to nearest integer)"""

gold_orders = df[df['membership_type'] == 'Gold'].shape[0]
total_orders = df.shape[0]

percent_gold = round((gold_orders / total_orders) * 100)
percent_gold

"""Which restaurant has the highest average order value but less than 20 total orders?

"""

restaurant_stats = df.groupby('restaurant_name').agg(
    avg_order_value=('total_amount', 'mean'),
    total_orders=('order_id', 'count')
)

restaurant_stats[
    restaurant_stats['total_orders'] < 20
].sort_values(by='avg_order_value', ascending=False)

"""Which combination contributes the highest revenue?

"""

df[df['restaurant_name'] == 'Hotel Dhaba Multicuisine']['cuisine'].unique()

df.groupby(['membership_type', 'cuisine'])['total_amount'] \
  .sum() \
  .sort_values(ascending=False)

"""During which quarter of the year is the total revenue highest?

"""

df['order_date'] = pd.to_datetime(df['order_date'])
df['quarter'] = df['order_date'].dt.quarter
df.groupby('quarter')['total_amount'].sum().sort_values(ascending=False)

"""How many total orders were placed by users with Gold membership?

"""

gold_orders_count = df[df['membership_type'] == 'Gold'].shape[0]
gold_orders_count

"""What is the total revenue (rounded to nearest integer) generated from orders placed in Hyderabad city?"""

hyderabad_revenue = df[df['city'] == 'Hyderabad']['total_amount'].sum()
round(hyderabad_revenue)

"""How many distinct users placed at least one order?

"""

distinct_users = df['user_id'].nunique()
distinct_users

"""What is the average order value (rounded to 2 decimals) for Gold members ?

"""

gold_aov = df[df['membership_type'] == 'Gold']['total_amount'].mean()
round(gold_aov, 2)

"""How many orders were placed for restaurants with rating ≥ 4.5?"""

high_rating_orders = df[df['rating'] >= 4.5].shape[0]
high_rating_orders

"""
How many orders were placed in the top revenue city among Gold members only?
```
# This is formatted as code
```

"""

gold_city_revenue = df[df['membership_type'] == 'Gold'].groupby('city')['total_amount'].sum()
top_city = gold_city_revenue.idxmax()
top_city

gold_orders_top_city = df[(df['membership_type'] == 'Gold') & (df['city'] == top_city)].shape[0]
gold_orders_top_city

"""The total number of rows in the final merged dataset is __________"""

import pandas as pd

df = pd.read_csv("/content/final_food_delivery_dataset.csv")
total_rows = df.shape[0]
total_rows
